stag_node:
  ros__parameters:
    tags: "[]"
    bundles:
      "[
        {
          frame: 'bundle_2',
          tags: [
            {
              id: 27,
              corners: [
                [ -0.127,  0.059, 0.0 ],
                [ -0.009,  0.059, 0.0 ],
                [ -0.009, -0.059, 0.0 ]
              ]
            },
            {
              id: 63,
              corners: [
                [ 0.009,  0.059, 0.0 ],
                [ 0.127,  0.059, 0.0 ],
                [ 0.127, -0.059, 0.0 ]
              ]
            }
          ]
        }
      ]"

# Marker corner order:
# 1          2
#  HD########
#  #ID#  ####
#  ##  ##  ##
#  ####  ####
#  ##########
# 4          3
