stag_node:
  ros__parameters:
    tags: "[]"
    bundles:
      "[
        {
          frame: 'bundle_4',
          tags: [
            {
              id: 76,
              corners: [
                [ -0.100,  0.095, 0.0 ],
                [ -0.011,  0.095, 0.0 ],
                [ -0.011,  0.006, 0.0 ]
              ]
            },
            {
              id: 92,
              corners: [
                [ -0.100, -0.006, 0.0 ],
                [ -0.011, -0.006, 0.0 ],
                [ -0.011, -0.095, 0.0 ]
              ]
            },
            {
              id: 103,
              corners: [
                [ 0.011,  0.095, 0.0 ],
                [ 0.100,  0.095, 0.0 ],
                [ 0.100,  0.006, 0.0 ]
              ]
            },
            {
              id: 138,
              corners: [
                [ 0.011, -0.006, 0.0 ],
                [ 0.100, -0.006, 0.0 ],
                [ 0.100, -0.095, 0.0 ]
              ]
            }
          ]
        }
      ]"

# Marker corner order:
# 1          2
#  HD########
#  #ID#  ####
#  ##  ##  ##
#  ####  ####
#  ##########
# 4          3
